version: '3'

services:   
    web:
        container_name:
            web_adwokat
        image:
            nginx:latest
        build:
            context: .
            dockerfile: nginx.Dockerfile  
        ports:
            - "8000:80" 
        tty: true            
        volumes:
            - ./app:/app     
            - ./default.conf:/etc/nginx/conf.d/default.conf          
        networks:
            - app-network
    fpm:
        image:
            php:8-fpm
        build:
            context: .
            dockerfile: fpm.Dockerfile              
        volumes:
            - ./app:/app 
        ports:
            - "9000:9000" 
        networks:
            - app-network 
    php:
        image:
            php:8.0.8-cli-alpine3.13
        build:
            context: .
            dockerfile: php.Dockerfile   
        tty: true                        
        volumes:
            - ./app:/app  
        networks:
            - app-network  
    db:
        image: "mariadb:latest"
        restart: 'always'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80           
        networks:
            - app-network                                        
networks:
    app-network:
        driver: bridge